
export const metadata = {
  title: "Landing Page App",
  description: "Generated by Ezone Next Js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
